name: Build manifest
on:
  push:
    paths:
      - 'images/**'
      - 'build_manifest.R'
      - '.github/workflows/build-manifest.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # erlaubt Commit zurück ins Repo
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: |
          Rscript -e "install.packages(c('jsonlite','stringr','dplyr','lubridate','purrr','fs'), repos='https://cloud.r-project.org')"
      - name: Build manifest
        run: |
          Rscript -e "source('build_manifest.R'); build_manifest(root='images', base_url='images/')"
      - name: Commit manifest.json
        uses: EndBug/add-and-commit@v9
        with:
          add: "manifest.json"
          message: "chore: update manifest.json"
